#!/usr/bin/env php
<?php declare(strict_types=1);
/** vim: set noet ts=4 sw=4 fdm=indent: */

set_time_limit(0);
ini_set('display_errors', 'on');
ini_set('memory_limit', '1024m');

require 'vendor/autoload.php';

require_once 'VarStackVisitor.php';

use PhpParser\{Node, NodeFinder};
use PhpParser\{Parser, ParserFactory};
use TonyParser\{VarStackVisitor};

function usage() {
	global $argv;
	echo "Usage: ./$argv[0] -t <target_file_or_dir_to_parse> -s [section_to_show]\n";
}

$args = getopt('t:s:v');
if (empty($args['t'])) {
	usage();
	exit;
}

$visitor = new VarStackVisitor($args['t']);
$visitor->traverse();
$visitor->dumpVars();

function __show_vars($vars)
{
	foreach ($vars as $name => $vals) {
		if (count($vals) == 1) {
			printf("  %s => %s (at line: %d)\n", $name, __expr($vals[0]), $vals[0]->getStartLine());
			continue;
		}
		echo "  $name => [\n";
		foreach ($vals as $val) {
			printf("    %s (at line: %d)\n", __expr($val), $val->getStartLine());
		}
		echo "  ];\n";
	}
}

function __expr($val)
{
	if ($val instanceof Node\Scalar && !$val instanceof Node\Scalar\Encapsed) {
		return $val->value;
	}
	return $val->getType();
}
