#!/usr/bin/env php
<?php declare(strict_types=1);
/** vim: set noet ts=4 sw=4 fdm=indent: */

require 'vendor/autoload.php';

require 'VarStackVisitor.php';

use PhpParser\{Node, NodeFinder};
use PhpParser\{Parser, ParserFactory};
use TonyParser\{VarStackVisitor};

function usage() {
	global $argv;
	echo "Usage: php $argv[0] <file_to_parse> [verbose] [debug]\n";
}

$target = $argv[1];
if (empty($target)) {
	usage();
	exit;
}

$verbose = false;
if (count($argv) >= 3 && $argv[2]) {
	$verbose = true;
}

$debug = false;
if (count($argv) >= 4 && $argv[3]) {
	$debug = true;
}

$visitor = new VarStackVisitor($target);
$visitor->traverse();
foreach ($visitor->getVarStacks() as $target => $vars) {
	echo "=== $target ===\n";
	foreach ($vars as $name => $val) {
		echo "  $name => " . get_class($val) . "\n";
	}
}

